name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/lib/android/sdk/platforms
            /usr/local/lib/android/sdk/system-images
            /usr/local/lib/android/sdk/build-tools
            /usr/local/lib/android/sdk/platform-tools
            /usr/local/lib/android/sdk/emulator
          key: android-sdk-34-${{ runner.os }}
          restore-keys: |
            android-sdk-34-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Android App
        run: wget https://github.com/appium/android-apidemos/releases/download/v3.1.0/ApiDemos-debug.apk

      - name: Install and run Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Run tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: google_apis
          arch: x86_64
          emulator-boot-timeout: 120
          api-level: 34 # You can change this to your desired API level
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script:
            appium &
            sleep 15
            pytest -o env=github_actions_android